### ISSUE TITLE
Any plan to add works that combine GNN and RL?

### ISSUE THREAD

**Issue by FeiGSSS** [SunQingYun1996/Graph-Reinforcement-Learning-Papers#1]
A lot of works focus on utilizing GNN and RL to solve combinational problems on graphs. Are they lie in the scope of your collection?

**Comment by SunQingYun1996** [comment]
That's one of the directions I'm interested in, and I'll add it to the list :)

**Comment by FeiGSSS** [comment]
Part of the papers in this collection now are "RL enhanced" GNNs in which the RL module is used to optimize the discrete operators in GNNs. But the branch I mentioned above always uses the RL as the downstream operator of GNNs (take actions based on outputs of GNNs).  Therefore, I suggest not making them mixed when you add other papers.

**Comment by SunQingYun1996** [comment]
Thank you for your advice and I'll take it！
